apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    app: {{ include "backend.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend.name" . }}
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: root-username

            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: root-password

            - name: MONGO_AUTH_SOURCE
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongo-auth-db

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-secret

            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: groq-api-key

            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mongo-host

            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: mongo-port

            - name: CORS_ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: backend-config
                  key: cors-origin
