apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: {{ include "backend.name" . }}
type: Opaque
data:
  root-username: {{ .Values.secret.mongoSecrets.username | b64enc | quote }}
  root-password: {{ .Values.secret.mongoSecrets.password | b64enc | quote }}
  mongo-auth-db: {{ .Values.secret.mongoSecrets.authDb | b64enc | quote }}
  jwt-secret: {{ .Values.secret.appSecrets.jwtSecret | b64enc | quote }}
  groq-api-key: {{ .Values.secret.appSecrets.groqApiKey | b64enc | quote }}
