replicaCount: 2

image:
  repository: shiva9828/frontend-mg
  tag: "v1-3"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: qtgem.com
      paths:
        - path: /
          pathType: Prefix

env:
  apiUrl: "http://backend:3000"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
