apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  root-username: {{ .Values.secret.rootUsername | b64enc | quote }}
  root-password: {{ .Values.secret.rootPassword | b64enc | quote }}
  mongo-auth-db: {{ .Values.secret.authDatabase | b64enc | quote }}