apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: mongo-service
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: mongo

  template:
    metadata:
      labels:
        app: mongo

    spec:
      containers:
        - name: mongo
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          args:
            - "--auth"
            - "--bind_ip_all"

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: root-password

          volumeMounts:
            - name: mongo-data
              mountPath: /data/db

          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  mongosh -u $MONGO_INITDB_ROOT_USERNAME
                  -p $MONGO_INITDB_ROOT_PASSWORD
                  --authenticationDatabase admin
                  --eval "db.adminCommand('ping')"
            initialDelaySeconds: 20
            periodSeconds: 5

          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - >
                  mongosh -u $MONGO_INITDB_ROOT_USERNAME
                  -p $MONGO_INITDB_ROOT_PASSWORD
                  --authenticationDatabase admin
                  --eval "db.adminCommand('ping')"
            initialDelaySeconds: 30
            periodSeconds: 10

  volumeClaimTemplates:
    - metadata:
        name: mongo-data

      spec:
        accessModes:
          - ReadWriteOnce

        storageClassName: {{ .Values.storage.className }}

        resources:
          requests:
            storage: {{ .Values.storage.size }}